# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  billogram_username: <%= ENV["BILLOGRAM_USERNAME"] %>
  billogram_password: <%= ENV["BILLOGRAM_PASSWORD"] %>
  github_token: <%= ENV["GITHUB_TOKEN"] %>
  front_token: <%= ENV["FRONT_TOKEN"] %>
  secret_key_base: a4476ac317147e973679d6db83a3eda774a4b820c0ccedcc6f27480f9a22004808217e6ae64fd29b0d9a92a26d32b7f2c39fbb9567fc229f9fd92ceee0d79e05

test:
  billogram_username:
  billogram_password:
  github_token:
  front_token:
  secret_key_base: 57ccd3de0a3d46e78aea5da7c67c9aafc670078eedc376b7b7bc72e7632f85a38e50f930b9f7ab0693c1bd7896f0e313739baedb900a741920037806fd222d77
